version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "exchange"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-c8smv7xrqzda"
s3_prefix = "exchange"
region = "eu-central-1"
profile = "daniel"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"ExchangeProd\""

